const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desktopAPI', {
  getBackupPath: () => ipcRenderer.invoke('backup:getPath'),
  saveBackup: (content) => ipcRenderer.invoke('backup:save', content),
  loadBackup: () => ipcRenderer.invoke('backup:load'),
  changeBackupPath: () => ipcRenderer.invoke('backup:changePath'),
  exportBackupOnce: (content, suggestedName) => ipcRenderer.invoke('backup:exportOnce', content, suggestedName),
  getDataLocation: () => ipcRenderer.invoke('data:getLocation'),
  chooseDataLocation: () => ipcRenderer.invoke('data:chooseLocation'),
  resetDataLocationToDefault: () => ipcRenderer.invoke('data:resetLocationToDefault'),
  restartApp: () => ipcRenderer.invoke('app:restart'),
  getAiExportInfo: () => ipcRenderer.invoke('data:getAiExportInfo'),
  regenerateAiExports: (journals) => ipcRenderer.invoke('data:regenerateAiExports', journals),
  writeAiExportManifest: (journals) => ipcRenderer.invoke('data:writeAiExportManifest', journals),
  factoryReset: () => ipcRenderer.invoke('app:factoryReset'),
  readJournal: (journalId) => ipcRenderer.invoke('storage:read', journalId),
  writeJournal: (journalId, data) => ipcRenderer.invoke('storage:write', journalId, data),
  deleteJournal: (journalId) => ipcRenderer.invoke('storage:deleteJournal', journalId),
  resetStorage: () => ipcRenderer.invoke('storage:reset'),
  captureStatus: () => ipcRenderer.invoke('capture:status'),
  captureEvents: (includeImported=false) => ipcRenderer.invoke('capture:events', includeImported),
  captureMarkImported: (ids) => ipcRenderer.invoke('capture:markImported', ids),
  captureClear: () => ipcRenderer.invoke('capture:clear'),
  captureClearPositions: () => ipcRenderer.invoke('capture:clearPositions'),
  captureSetAutoImport: (value) => ipcRenderer.invoke('capture:setAutoImport', value),
  captureRegenerateKey: () => ipcRenderer.invoke('capture:regenerateKey'),
  captureSetScreenshotMode: (mode) => ipcRenderer.invoke('capture:setScreenshotMode', mode),
  captureSetMappings: (mappings) => ipcRenderer.invoke('capture:setMappings', mappings),
  captureSetHiddenAccounts: (accounts) => ipcRenderer.invoke('capture:setHiddenAccounts', accounts),
  captureDeleteAccount: (account) => ipcRenderer.invoke('capture:deleteAccount', account),
  captureSetRelay: (relay) => ipcRenderer.invoke('capture:setRelay', relay),
  capturePollRelay: () => ipcRenderer.invoke('capture:pollRelay'),
  captureReadScreenshot: (filePath) => ipcRenderer.invoke('capture:readScreenshot', filePath),
  captureTestExecutionSequence: () => ipcRenderer.invoke('capture:testExecutionSequence'),
  captureTestMultiTargetSequence: () => ipcRenderer.invoke('capture:testMultiTargetSequence'),
  captureTestCTraderSequence: () => ipcRenderer.invoke('capture:testCTraderSequence'),
  captureInstallCTraderConnector: () => ipcRenderer.invoke('capture:installCTraderConnector'),
  captureExportCTraderConnector: () => ipcRenderer.invoke('capture:exportCTraderConnector'),
  copyImageToClipboard: (dataUrl) => ipcRenderer.invoke('image:copyToClipboard', dataUrl),
  openImageExternally: (dataUrl) => ipcRenderer.invoke('image:openExternally', dataUrl),
  saveImageAs: (dataUrl) => ipcRenderer.invoke('image:saveAs', dataUrl),
  captureInstallNinjaConnector: () => ipcRenderer.invoke('capture:installNinjaConnector'),
  capturePrepareTradingViewPine: () => ipcRenderer.invoke('capture:prepareTradingViewPine'),
  capturePrepareTradingViewWorker: () => ipcRenderer.invoke('capture:prepareTradingViewWorker'),
  captureExportNinjaConnector: () => ipcRenderer.invoke('capture:exportNinjaConnector'),
  captureExportTradingViewConnector: () => ipcRenderer.invoke('capture:exportTradingViewConnector'),
  captureExportTradingViewWorker: () => ipcRenderer.invoke('capture:exportTradingViewWorker'),
  captureOpenConnectorFolder: () => ipcRenderer.invoke('capture:openConnectorFolder'),
  onCaptureEvent: (callback) => ipcRenderer.on('capture:event', (_event, payload) => callback(payload))
});
