const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desktopAPI', {
  getBackupPath: () => ipcRenderer.invoke('backup:getPath'),
  changeBackupPath: () => ipcRenderer.invoke('backup:changePath'),
  exportBackupOnce: (content, suggestedName) => ipcRenderer.invoke('backup:exportOnce', content, suggestedName),
  // Zálohy všech deníků skládá a rozebírá hlavní proces – obsahují screenshoty
  // a přes IPC by to byly desítky až stovky MB v jedné zprávě.
  saveJournalsBackup: (meta) => ipcRenderer.invoke('backup:saveJournals', meta),
  restoreJournalsBackup: () => ipcRenderer.invoke('backup:restoreJournals'),
  exportJournalOnce: (journalId, suggestedName) => ipcRenderer.invoke('backup:exportJournalOnce', journalId, suggestedName),
  getDataLocation: () => ipcRenderer.invoke('data:getLocation'),
  chooseDataLocation: () => ipcRenderer.invoke('data:chooseLocation'),
  resetDataLocationToDefault: () => ipcRenderer.invoke('data:resetLocationToDefault'),
  restartApp: () => ipcRenderer.invoke('app:restart'),
  getAiExportInfo: () => ipcRenderer.invoke('data:getAiExportInfo'),
  regenerateAiExports: (journals) => ipcRenderer.invoke('data:regenerateAiExports', journals),
  writeAiExportManifest: (journals) => ipcRenderer.invoke('data:writeAiExportManifest', journals),
  factoryReset: () => ipcRenderer.invoke('app:factoryReset'),
  readJournal: (journalId) => ipcRenderer.invoke('storage:read', journalId),
  writeJournal: (journalId, data) => ipcRenderer.invoke('storage:write', journalId, data),
  backupJournal: (journalId, reason) => ipcRenderer.invoke('storage:backupJournal', journalId, reason),
  deleteJournal: (journalId) => ipcRenderer.invoke('storage:deleteJournal', journalId),
  resetStorage: () => ipcRenderer.invoke('storage:reset'),
  captureStatus: () => ipcRenderer.invoke('capture:status'),
  captureEvents: (includeImported=false) => ipcRenderer.invoke('capture:events', includeImported),
  captureMarkImported: (ids) => ipcRenderer.invoke('capture:markImported', ids),
  captureClear: () => ipcRenderer.invoke('capture:clear'),
  captureClearPositions: () => ipcRenderer.invoke('capture:clearPositions'),
  captureSetAutoImport: (value) => ipcRenderer.invoke('capture:setAutoImport', value),
  captureRegenerateKey: () => ipcRenderer.invoke('capture:regenerateKey'),
  captureSetScreenshotMode: (mode) => ipcRenderer.invoke('capture:setScreenshotMode', mode),
  captureAddAccount: (account) => ipcRenderer.invoke('capture:addAccount', account),
  captureSetMappings: (mappings) => ipcRenderer.invoke('capture:setMappings', mappings),
  captureSetHiddenAccounts: (accounts) => ipcRenderer.invoke('capture:setHiddenAccounts', accounts),
  captureDeleteAccount: (account) => ipcRenderer.invoke('capture:deleteAccount', account),
  captureSetRelay: (relay) => ipcRenderer.invoke('capture:setRelay', relay),
  capturePollRelay: () => ipcRenderer.invoke('capture:pollRelay'),
  captureReadScreenshot: (filePath) => ipcRenderer.invoke('capture:readScreenshot', filePath),
  captureTestExecutionSequence: () => ipcRenderer.invoke('capture:testExecutionSequence'),
  captureTestMultiTargetSequence: () => ipcRenderer.invoke('capture:testMultiTargetSequence'),
  captureTestCTraderSequence: () => ipcRenderer.invoke('capture:testCTraderSequence'),
  captureTestSnapshotRaceSequence: () => ipcRenderer.invoke('capture:testSnapshotRaceSequence'),
  captureInstallCTraderConnector: () => ipcRenderer.invoke('capture:installCTraderConnector'),
  captureExportCTraderConnector: () => ipcRenderer.invoke('capture:exportCTraderConnector'),
  copyImageToClipboard: (source) => ipcRenderer.invoke('image:copyToClipboard', source),
  openImageExternally: (source) => ipcRenderer.invoke('image:openExternally', source),
  saveImageAs: (source) => ipcRenderer.invoke('image:saveAs', source),
  // Uloží jeden obrázek do úložiště screenshotů a vrátí krátký odkaz, který
  // se zapíše k obchodu místo base64.
  storeImage: (dataUrl) => ipcRenderer.invoke('image:store', dataUrl),
  storeCaptureImage: (filePath) => ipcRenderer.invoke('image:storeCapture', filePath),
  captureInstallNinjaConnector: () => ipcRenderer.invoke('capture:installNinjaConnector'),
  capturePrepareTradingViewPine: () => ipcRenderer.invoke('capture:prepareTradingViewPine'),
  capturePrepareTradingViewWorker: () => ipcRenderer.invoke('capture:prepareTradingViewWorker'),
  captureExportNinjaConnector: () => ipcRenderer.invoke('capture:exportNinjaConnector'),
  captureExportTradingViewConnector: () => ipcRenderer.invoke('capture:exportTradingViewConnector'),
  captureExportTradingViewWorker: () => ipcRenderer.invoke('capture:exportTradingViewWorker'),
  captureOpenConnectorFolder: () => ipcRenderer.invoke('capture:openConnectorFolder'),
  onCaptureEvent: (callback) => ipcRenderer.on('capture:event', (_event, payload) => callback(payload))
});
